
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The ErfassungOhneAuftrag controller entity class.
 * @author
 *    Guy Bami Watcho
 */
include_once 'BaseController.php';

class ErfassungOhneAuftragController extends BaseController {

    private $erfassungOhneAuftrag = null;

    /**
     * Constructor of the ErfassungOhneAuftrag controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->erfassungOhneAuftrag = new ErfassungOhneAuftrag();
    }

    /**
     * Gets all ErfassungOhneAuftrag entities
     * @return mixed object having all ErfassungOhneAuftrag entities
     *    or string with the Exception details if error occured
     */
    public function getAllErfassungOhneAuftrags() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->erfassungOhneAuftrag->selectAllErfassungOhneAuftrags();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"erfassungId":"' . $resultObject[$i]["erfassungId"] . '"'
                        . ',"kundenNummer":"' . $resultObject[$i]["kundenNummer"] . '"'
                        . ',"bericht":"' . $resultObject[$i]["bericht"] . '"'
                        . ',"material":"' . $resultObject[$i]["material"] . '"'
                        . ',"maschineAufwand":"' . $resultObject[$i]["maschineAufwand"] . '"'
                        . ',"kilometer":"' . $resultObject[$i]["kilometer"] . '"'
                        . ',"unterschriftMitarbeiterDatei":"' . $resultObject[$i]["unterschriftMitarbeiterDatei"] . '"'
                        . ',"unterschriftKundeDatei":"' . $resultObject[$i]["unterschriftKundeDatei"] . '"'
                        . ',"auftragAbgeschlossen":"' . $resultObject[$i]["auftragAbgeschlossen"] . '"'
                        . ',"datum":"' . $resultObject[$i]["datum"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new ErfassungOhneAuftrag entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewErfassungOhneAuftrag($jsonData) {

        // get json posted values from request
        //$formJsonValues = json_decode($jsonData, true);
        $formJsonValues = $jsonData;
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->erfassungOhneAuftrag->insertNewErfassungOhneAuftrag(
                $formJsonValues['kundenNummer']
                , $formJsonValues['bericht']
                , $formJsonValues['material']
                , $formJsonValues['maschineAufwand']
                , $formJsonValues['kilometer']
                , $formJsonValues['unterschriftMitarbeiterDatei']
                , $formJsonValues['unterschriftKundeDatei']
                , $formJsonValues['auftragAbgeschlossen']
                , $formJsonValues['datum']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates ErfassungOhneAuftrag entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateErfassungOhneAuftrag($erfassungId, $updateMode, $jsonData) {

        // get json posted values from request
        //$formJsonValues = json_decode($jsonData, true);
        $formJsonValues = $jsonData;
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->erfassungOhneAuftrag->updateErfassungOhneAuftragDetails(
                    $erfassungId
                    , $formJsonValues['kundenNummer']
                    , $formJsonValues['bericht']
                    , $formJsonValues['material']
                    , $formJsonValues['maschineAufwand']
                    , $formJsonValues['kilometer']
                    , $formJsonValues['unterschriftMitarbeiterDatei']
                    , $formJsonValues['unterschriftKundeDatei']
                    , $formJsonValues['auftragAbgeschlossen']
                    , $formJsonValues['datum']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->erfassungOhneAuftrag->updateErfassungOhneAuftragEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteErfassungOhneAuftrags($jsonData) {

        // delete entity using model
        $resultObject = $this->erfassungOhneAuftrag->deleteSelectedErfassungOhneAuftrags($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllErfassungOhneAuftrags() {

        // delete entities using corresponding model
        $resultObject = $this->erfassungOhneAuftrag->deleteAllErfassungOhneAuftrags();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllErfassungOhneAuftrags();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewErfassungOhneAuftrag($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $erfassungId = $_POST['erfassungId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateErfassungOhneAuftrag($erfassungId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteErfassungOhneAuftrags($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllErfassungOhneAuftrags();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['erfassungId'])) {
                    $erfassungId = $_POST['erfassungId'];
                    $resultObject = $this->erfassungOhneAuftrag->getErfassungOhneAuftragDetails($erfassungId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['erfassungId'])) {
                    $erfassungId = $_POST['erfassungId'];
                    $resultObject = $this->erfassungOhneAuftrag->getErfassungOhneAuftragDetails($erfassungId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
        }
        return $postbackData;
    }

}

if ($_SERVER['CONTENT_TYPE'] === "application/json; charset=UTF-8" || $_SERVER['CONTENT_TYPE'] === "application/json") {
    $jsonRaw = file_get_contents("php://input");

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
} else if (isset($_GET) && isset($_GET['userAction'])) {
    $userAction = $_GET['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    Utils::logRequestToFile($userAction);
    $erfassungOhneAuftragController = new ErfassungOhneAuftragController($userAction);
    $erfassungOhneAuftragController->setUserAction($userAction);
    $postbackContent = $erfassungOhneAuftragController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

