
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Montage controller entity class.
 * @author
 *    Guy Bami Watcho
 */
include_once 'BaseController.php';

class MontageController extends BaseController {

    private $montage = null;

    /**
     * Constructor of the Montage controller 

     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->montage = new Montage();
    }

    /**
     * Gets all Montage entities
     * @return mixed object having all Montage entities
     *    or string with the Exception details if error occured
     */
    public function getAllMontages() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->montage->selectAllMontages();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"montageId":"' . $resultObject[$i]["montageId"] . '"'
                        . ',"rapportId":"' . $resultObject[$i]["rapportId"] . '"'
                        . ',"bericht":"' . $resultObject[$i]["bericht"] . '"'
                        . ',"aufnahmeUnterschriftDatei":"' . $resultObject[$i]["aufnahmeUnterschriftDatei"] . '"'
                        . ',"auftragAbgeschlossen":"' . $resultObject[$i]["auftragAbgeschlossen"] . '"'
                        . ',"datum":"' . $resultObject[$i]["datum"] . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new Montage entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewMontage($jsonData) {

        // get json posted values from request
        //$formJsonValues = json_decode($jsonData, true);
        $formJsonValues = $jsonData;
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->montage->insertNewMontage(
                $formJsonValues['rapportId']
                , $formJsonValues['bericht']
                , $formJsonValues['aufnahmeUnterschriftDatei']
                , $formJsonValues['auftragAbgeschlossen']
                , $formJsonValues['datum']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates Montage entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateMontage($montageId, $updateMode, $jsonData) {

        // get json posted values from request
        //$formJsonValues = json_decode($jsonData, true);
        $formJsonValues = $jsonData;
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->montage->updateMontageDetails(
                    $montageId
                    , $formJsonValues['rapportId']
                    , $formJsonValues['bericht']
                    , $formJsonValues['aufnahmeUnterschriftDatei']
                    , $formJsonValues['auftragAbgeschlossen']
                    , $formJsonValues['datum']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->montage->updateMontageEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteMontages($jsonData) {

        // delete entity using model
        $resultObject = $this->montage->deleteSelectedMontages($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllMontages() {

        // delete entities using corresponding model
        $resultObject = $this->montage->deleteAllMontages();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }
    
    
    
    function checkData($formJsonValues) {
        // check data
        echo 'formJsonValues: ';
        print_r($formJsonValues);
        echo '<br /><br />';

        echo 'skizzeFilesList: ';
        print_r($_POST['skizzeFilesList']);
        echo '<br /><br />';

        echo 'bilderFilesList: ';
        print_r($_POST['bilderFilesList']);
        echo '<br /><br />';

        echo 'arbeitszeitList: ';
        print_r($_POST['arbeitszeitList']);
        echo '<br /><br />';
    }

    function addNewItemWithRelatedEntities($jsonData) {

        $formJsonValues = $jsonData;

        // step1: insert Montage
        $resultObject = null;
        $montageId = "";
        $montageBild = new MontageBild();
        $arbeitszeit = new Arbeitszeit();
        $postbackData = "-";
        $daoSelect = new DaoSelect();


        // insert entity using model object
        $resultObject = $this->montage->insertNewMontage(
                $formJsonValues['rapportId']
                , $formJsonValues['bericht']
                , $formJsonValues['aufnahmeUnterschriftDatei']
                , $formJsonValues['auftragAbgeschlossen']
                , $formJsonValues['datum']
        );
            
        if (is_int($resultObject)) {
            $montageId = $resultObject;
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
            
            // step 2: insert Bilder vor der Arbeit
            $arrayBilderVorArbeit = array();
            //step 2.1: get all images before work for this Montage
            $daoSelect = new DaoSelect();
            $arrayBilderVorArbeit = $daoSelect->selectAllBilderVorArbeitByMontage($montageId);
            //step 2.2: delete
            $arrayBilderVorArbeitId = array();
            foreach (array_values($arrayBilderVorArbeit) as $arrayItem) {
                array_push($arrayBilderVorArbeitId, $arrayItem['bildId']);
            }
            $montageBild->deleteSelectedMontageBilds($arrayBilderVorArbeitId);
            // step 2.3 insert new array
            $countSkizze = 0;
            $newArraySkizzeToInsert = $_POST['bilderVorArbeitFilesList'];
            foreach (array_values($newArraySkizzeToInsert) as $fileName) {
                // insert entity using model object
                $resultObject = $montageBild->insertNewMontageBild(
                        $montageId
                        , 'vorArbeit'
                        , $fileName
                );
                if (is_bool($resultObject) || is_int($resultObject)) {
                    $countSkizze++;
                }
            }


             
 
            // step 3: insert Bilder nach der Arbeit
            $arrayBilderNachArbeit = array();
            //step 3.1: get all images before work for this Montage
            $daoSelect = new DaoSelect();
            $arrayBilderNachArbeit = $daoSelect->selectAllBilderNachArbeitByMontage($montageId);
            //step 3.2: delete
            $arrayBilderNachArbeitId = array();
            foreach (array_values($arrayBilderNachArbeit) as $arrayItem) {
                array_push($arrayBilderNachArbeitId, $arrayItem['bildId']);
            }
            $montageBild->deleteSelectedMontageBilds($arrayBilderNachArbeitId);
            // step 3.3 insert new array
            $countSkizze = 0;
            $newArraySkizzeToInsert = $_POST['bilderNachArbeitFilesList'];
            foreach (array_values($newArraySkizzeToInsert) as $fileName) {
                // insert entity using model object
                $resultObject = $montageBild->insertNewMontageBild(
                        $montageId
                        , 'nachArbeit'
                        , $fileName
                );
                if (is_bool($resultObject) || is_int($resultObject)) {
                    $countSkizze++;
                }
            }


            // step 4: insert Arbeitszeit
            $arrayZeiten = array();
            //step 4.1: get all entries for this Montage
            $arrayZeiten = $daoSelect->selectAllArbeitszeitByMontage($formJsonValues['rapportId']);
            $arrayArbeitszeitId = array();
            foreach (array_values($arrayZeiten) as $arrayItem) {
                array_push($arrayArbeitszeitId, $arrayItem['arbeitszeitId']);
            }
            //step 4.2: delete
            $arbeitszeit->deleteSelectedArbeitszeits($arrayArbeitszeitId);
            // step 4.3 insert new array

            $newArrayArbeitszeit = $_POST['arbeitszeitList'];
            foreach (array_values($newArrayArbeitszeit) as $arrayItem) {
                // insert entity using model object
                $resultObject = $arbeitszeit->insertNewArbeitszeit(
                        $arrayItem['rapportId']
                        , "Montage"
                        , $arrayItem['mitarbeiterName']
                        , $arrayItem['gruppe']
                        , $arrayItem['zeit']
                        , $arrayItem['datum']
                );
            }
        }

        return $postbackData;
    }

    function updateItemWithRelatedEntities($jsonData) {

        $formJsonValues = $jsonData;

        $resultObject = null;
        $montageBild = new MontageBild();
        $arbeitszeit = new Arbeitszeit();
        $postbackData = "-";
        $montageId = '0';
        $daoSelect = new DaoSelect();

        if (isset($formJsonValues['rapportId']))
            $rapportId = $formJsonValues['rapportId'];

        // step 1: get MontageId from rapport
        $resultObject = $daoSelect->selectRapportMontageDatails($rapportId);
        if (is_array($resultObject)) {
            $montageId = $resultObject[0]['montageId'];
        }

        // update  entity using model object
        $resultObject = $this->montage->updateMontageDetails(
                    $montageId
                    , $formJsonValues['rapportId']
                    , $formJsonValues['bericht']
                    , $formJsonValues['aufnahmeUnterschriftDatei']
                    , $formJsonValues['auftragAbgeschlossen']
                    , $formJsonValues['datum']
            );

        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_SUCCESSFUL);
            }

            // step 2: insert Bilder vor der Arbeit
            $arrayBilderVorArbeit = array();
            //step 2.1: get all images before work for this Montage
            $daoSelect = new DaoSelect();
            $arrayBilderVorArbeit = $daoSelect->selectAllBilderVorArbeitByMontage($montageId);
            //step 2.2: delete
            $arrayBilderVorArbeitId = array();
            foreach (array_values($arrayBilderVorArbeit) as $arrayItem) {
                array_push($arrayBilderVorArbeitId, $arrayItem['bildId']);
            }
            $montageBild->deleteSelectedMontageBilds($arrayBilderVorArbeitId);
            // step 2.3 insert new array
            $countSkizze = 0;
            $newArraySkizzeToInsert = $_POST['bilderVorArbeitFilesList'];
            foreach (array_values($newArraySkizzeToInsert) as $fileName) {
                // insert entity using model object
                $resultObject = $montageBild->insertNewMontageBild(
                        $montageId
                        , 'vorArbeit'
                        , $fileName
                );
                if (is_bool($resultObject) || is_int($resultObject)) {
                    $countSkizze++;
                }
            }

 
            // step 3: insert Bilder nach der Arbeit
            $arrayBilderNachArbeit = array();
            //step 3.1: get all images before work for this Montage
            $daoSelect = new DaoSelect();
            $arrayBilderNachArbeit = $daoSelect->selectAllBilderNachArbeitByMontage($montageId);
            //step 3.2: delete
            $arrayBilderNachArbeitId = array();
            foreach (array_values($arrayBilderNachArbeit) as $arrayItem) {
                array_push($arrayBilderNachArbeitId, $arrayItem['bildId']);
            }
            $montageBild->deleteSelectedMontageBilds($arrayBilderNachArbeitId);
            // step 3.3 insert new array
            $countSkizze = 0;
            $newArraySkizzeToInsert = $_POST['bilderNachArbeitFilesList'];
            foreach (array_values($newArraySkizzeToInsert) as $fileName) {
                // insert entity using model object
                $resultObject = $montageBild->insertNewMontageBild(
                        $montageId
                        , 'nachArbeit'
                        , $fileName
                );
                if (is_bool($resultObject) || is_int($resultObject)) {
                    $countSkizze++;
                }
            }

            // step 4: insert Arbeitszeit
            $arrayZeiten = array();
            //step 4.1: get all entries for this Montage
            $arrayZeiten = $daoSelect->selectAllArbeitszeitByMontage($formJsonValues['rapportId']);
            $arrayArbeitszeitId = array();
            foreach (array_values($arrayZeiten) as $arrayItem) {
                array_push($arrayArbeitszeitId, $arrayItem['arbeitszeitId']);
            }
            //step 4.2: delete
            $arbeitszeit->deleteSelectedArbeitszeits($arrayArbeitszeitId);
            // step 4.3 insert new array

            $newArrayArbeitszeit = $_POST['arbeitszeitList'];
            foreach (array_values($newArrayArbeitszeit) as $arrayItem) {
                // insert entity using model object
                $resultObject = $arbeitszeit->insertNewArbeitszeit(
                        $arrayItem['rapportId']
                        , "Montage"
                        , $arrayItem['mitarbeiterName']
                        , $arrayItem['gruppe']
                        , $arrayItem['zeit']
                        , $arrayItem['datum']
                );
            }
        }

        return $postbackData;
    }
    
    

    function getDatailsItemWithRelatedEntities($rapportId) {

        $resultObject = null;
        $montageBild = new MontageBild();
        $arbeitszeit = new Arbeitszeit();
        $postbackData = "-";
        $montageId = '0';
        $daoSelect = new DaoSelect();
        $resultJson;

        // step 0: get MontageId from rapport
        $resultObject = $daoSelect->selectRapportMontageDatails($rapportId);
        if (is_array($resultObject)) {
            $montageId = $resultObject[0]['montageId'];
        }


        // step1: get Montage details
        if (isset($montageId)) {
            //$montageId = $_POST['montageId'];
            $resultObject = $this->montage->getMontageDetails($montageId);
        }

        if (is_array($resultObject)) {
            // formvalues

            $postbackData = Utils::removeNumericalKeys($resultObject[0]);

            // add key
            $resultJson->formValues = $postbackData;
            
            // step 2:
            //step 2.1: get all images before work for this Montage
            $daoSelect = new DaoSelect();
            $arrayBilderVorArbeit = $daoSelect->selectAllBilderVorArbeitByMontage($montageId);
            $arrayBilderVorArbeitFileNames = array();
            foreach (array_values($arrayBilderVorArbeit) as $arrayItem) {
                array_push($arrayBilderVorArbeitFileNames, $arrayItem['dateiName']);
            }
            if (is_array($arrayBilderVorArbeitFileNames))
                $resultJson->bilderVorArbeitFilesList = $arrayBilderVorArbeitFileNames;
            
            // step 3: get all images after work for this Montage
            $arrayBilderNachArbeit = $daoSelect->selectAllBilderNachArbeitByMontage($montageId);
            $arrayBilderNachArbeitFileNames = array();
            foreach (array_values($arrayBilderNachArbeit) as $arrayItem) {
                array_push($arrayBilderNachArbeitFileNames, $arrayItem['dateiName']);
            }
            if (is_array($arrayBilderNachArbeitFileNames))
                $resultJson->bilderNachArbeitFilesList = $arrayBilderNachArbeitFileNames;

            // step 4: arbeitszeiten
            $arrayZeiten = array();
            //step 4.1: get all entries for this Montage
            $arrayZeiten = $daoSelect->selectAllArbeitszeitByMontage($rapportId);
            $arrayZeitenCleaned = array();
            foreach (array_values($arrayZeiten) as $arrayItem) {
                $arrayBuf = Utils::removeNumericalKeys($arrayItem);
                array_push($arrayZeitenCleaned, $arrayBuf);
            }

            $resultJson->arbeitszeitList = $arrayZeitenCleaned;
        } else if (is_string($resultObject)) {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }


        $postbackData = "[" . json_encode($resultJson) . "]";
        //echo $postbackData;
        return $postbackData;
    }

    
    function getRapportMontageDatails($rapportId) {

        $resultObject = null;
        // echo '$rapportId: ' . $rapportId; 
        $daoSelect = new DaoSelect();
        $resultObject = $daoSelect->selectRapportMontageDatails($rapportId);
        //print_r($postbackData);
        return $resultObject;
    }


    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllMontages();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewMontage($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $montageId = $_POST['montageId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateMontage($montageId, $updateMode, $jsonData);
                break;
            case "deleteItem":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteMontages($jsonData);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllMontages();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['montageId'])) {
                    $montageId = $_POST['montageId'];
                    $resultObject = $this->montage->getMontageDetails($montageId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['montageId'])) {
                    $montageId = $_POST['montageId'];
                    $resultObject = $this->montage->getMontageDetails($montageId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "getRapportMontageDatails":
                if (isset($_POST['rapportId'])) {
                    $rapportId = $_POST['rapportId'];
                    $resultObject = $this->getRapportMontageDatails($rapportId);
                }

                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }

                break;
            case "addNewItemWithRelatedEntities":
                $postbackData = "Undefined Content";
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->addNewItemWithRelatedEntities($jsonData);
                break;
            case "updateItemWithRelatedEntities":
                $postbackData = "Undefined Content";
                $jsonData = array();

                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->updateItemWithRelatedEntities($jsonData);
                break;
            case "getDatailsItemWithRelatedEntities":
                $postbackData = "Undefined Content";
                $jsonData = array();

                if (isset($_POST['rapportId'])) {
                    $rapportId = $_POST['rapportId'];
                }
                $postbackData = $this->getDatailsItemWithRelatedEntities($rapportId);
                break;
        }
        return $postbackData;
    }

}



         
function testAddNewItem($rapportId) {

    $jsonRaw = '{"userAction":"addNewItem", "formValues":'
            . '[{"rapportId":"' . $rapportId . '"'
            . ',"bericht":" sdsd sd "'
            . ',"aufnahmeUnterschriftDatei":"signatur.jpg"'
            . ',"auftragAbgeschlossen":"nein"'
            . ',"datum":"2020-03-23 12:13:00"'
            . ' }]
              }';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testGetAllItems() {

    $jsonRaw = '{"userAction":"getAllItems"}';
    if (is_string($jsonRaw)) {
        $_POST = json_decode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testUpdateItem() {

    $jsonRaw = '{"userAction":"updateItem", "montageId":"1", "formValues":'
            . '[{"rapportId":"1"'
            . ',"bericht":" sdsd sd "'
            . ',"aufnahmeUnterschriftDatei":"signatur.jpg"'
            . ',"auftragAbgeschlossen":"nein"'
            . ',"datum":"2020-03-23 15:11:00"'
            . ' }]
              }';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testGetDatailsItem() {

    $jsonRaw = '{"userAction":"viewDetails", "montageId":"1"}';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

            
function testAddNewItemWithRelatedEntities($rapportId) {

    $jsonRaw = '{"userAction":"addNewItemWithRelatedEntities"'
            . ',"formValues":[{"rapportId":"' . $rapportId . '", "bericht":"this is bereicht", "aufnahmeUnterschriftDatei":"signatur.jpg",  "auftragAbgeschlossen":"nein", "datum":"2020-03-23 20:13:00"}]'
            . ',"bilderVorArbeitFilesList":["v-bild1.jpg", "v-bild2.jpg", "v-bild3.jpg"]'
            . ',"bilderNachArbeitFilesList":["n-bild1.jpg", "n-bild2.jpg", "n-bild3.jpg"]'
            . ',"arbeitszeitList":'
            . '[{"rapportId":"' . $rapportId . '" ,"bereich":"Montage", "mitarbeiterName":"Bami 1-montage", "gruppe":"AB-Gruppe-123", "zeit":"2", "datum":"2020-03-16 12:13:00"},'
            . ' {"rapportId":"' . $rapportId . '" ,"bereich":"Montage", "mitarbeiterName":"Sokoi 2montage", "gruppe":"AB-Gruppe-433", "zeit":"3", "datum":"2020-03-16 12:23:00"}]'
            . '}';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}




function testUpdateItemWithRelatedEntities($rapportId) {

    $jsonRaw = '{"userAction":"updateItemWithRelatedEntities" '
            . ',"formValues":[{"rapportId":"' . $rapportId . '", "bericht":"this is bereicht", "aufnahmeUnterschriftDatei":"signatur-new.jpg",  "auftragAbgeschlossen":"nein", "datum":"2020-03-23 20:13:00"}]'
            . ',"bilderVorArbeitFilesList":["v-bild1-new.jpg", "v-bild2-new.jpg", "v-bild3-new.jpg"]'
            . ',"bilderNachArbeitFilesList":["n-bild1-new.jpg", "n-bild2-new.jpg", "n-bild3-new.jpg"]'
            . ',"arbeitszeitList":'
            . '[{"rapportId":"' . $rapportId . '" ,"bereich":"Montage", "mitarbeiterName":"Bami 1-montage-new", "gruppe":"AB-Gruppe-123", "zeit":"2", "datum":"2020-03-20 12:13:00"},'
            . ' {"rapportId":"' . $rapportId . '" ,"bereich":"Montage", "mitarbeiterName":"Sokoi 2-new-montage", "gruppe":"AB-Gruppe-433", "zeit":"1", "datum":"2020-03-20 12:23:00"}]'
            . '}';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}


function testGetDatailsItemWithRelatedEntities($rapportId) {

    $jsonRaw = '{"userAction":"getDatailsItemWithRelatedEntities", "rapportId":"' . $rapportId . '"}';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testGetRapportMontageDatails($rapportId) {

    $jsonRaw = '{"userAction":"getRapportMontageDatails", "rapportId":"' . $rapportId . '"}';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}


$rapportId = "1";
//testAddNewItem($rapportId);
//testUpdateItem();
//testGetAllItems();
//testGetDatailsItem();
//testAddNewItemWithRelatedEntities($rapportId);
//testUpdateItemWithRelatedEntities($rapportId);
//testGetDatailsItemWithRelatedEntities($rapportId);
 //testGetRapportMontageDatails($rapportId);




if ($_SERVER['CONTENT_TYPE'] === "application/json; charset=UTF-8" || $_SERVER['CONTENT_TYPE'] === "application/json") {
    $jsonRaw = file_get_contents("php://input");

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
} else if (isset($_GET) && isset($_GET['userAction'])) {
    $userAction = $_GET['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} else {
    Utils::logRequestToFile($userAction);
    $montageController = new MontageController($userAction);
    $montageController->setUserAction($userAction);
    $postbackContent = $montageController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

