
            <?php 


               /**
                * This module was auto generated by GWatcho-Code generator
                * The NachtraegeSkizze controller entity class.
                * @author
                *    Guy Bami Watcho
                */

  
include_once 'BaseController.php';


 class NachtraegeSkizzeController extends BaseController { 
private $nachtraegeSkizze = null; 


                 /**
                  *Constructor of the NachtraegeSkizze controller 

                   * @param $userAction string the user action
* @param $userRoles array the user roles 
                  */
                
function __construct($userAction, $userRoles = array()){ 
     parent::__construct($userAction, $userRoles);
                        $this->nachtraegeSkizze = new NachtraegeSkizze(); }


           /**
            * Gets all NachtraegeSkizze entities
            * @return mixed object having all NachtraegeSkizze entities
            *    or string with the Exception details if error occured
            */
            public function getAllNachtraegeSkizzes(){

                $itemSperator = ",";
                $entitiesList = "";
                $resultObject = $this->nachtraegeSkizze->selectAllNachtraegeSkizzes();
                if(is_string($resultObject)){
                    return Utils::formatJsonErrorMessage($resultObject);
                }
                else if(is_array($resultObject)){
                    for ($i = 0; $i < count($resultObject); $i++)
                    {
                        $entitiesList .= 
'{"skizzeId":"'.$resultObject[$i]["skizzeId"].'"'
.',"nachtragId":"'.$resultObject[$i]["nachtragId"].'"'
.',"dateiName":"'.$resultObject[$i]["dateiName"].'"'
.'}';

                        if ($i != count($resultObject) - 1) {
                            $entitiesList .= $itemSperator;
                        }
                    }
                    // close json list
                    $entitiesList = "[" . $entitiesList . "]";

                }
                return $entitiesList;

            }


           /**
             * Inserts new NachtraegeSkizze entity
             * @param mixed $jsonData json object entity to insert
             * @return mixed  true if insertion was successful
             *    or string with the Exception details if error occured
             */
            public function insertNewNachtraegeSkizze($jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                // insert entity using model object
                $resultObject = $this->nachtraegeSkizze->insertNewNachtraegeSkizze(
                                $formJsonValues['nachtragId']
,$formJsonValues['dateiName']


                );

                if(is_bool($resultObject) || is_int($resultObject)){
                    $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Updates NachtraegeSkizze entity via POST request
             * @param int $customerId
             * @param string $updateMode
             * @param mixed $jsonData
             * @return mixed  true if update was successful
             *    or string with the Exception details if error occured
             */
            public function updateNachtraegeSkizze($skizzeId, $updateMode, $jsonData){

                // get json posted values from request
                $formJsonValues = json_decode($jsonData, true);
                $postbackData = "";
                $resultObject = null;
                if ($updateMode == "allFields") {
                    // update all entity fields
                    $resultObject = $this->nachtraegeSkizze->updateNachtraegeSkizzeDetails(
                                  $skizzeId
,$formJsonValues['nachtragId']
,$formJsonValues['dateiName']


                    );
                    if(is_bool($resultObject)){
                        if($resultObject == true){
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_SUCCESSFUL);
                        }
                        else{
                            $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_FAILED);
                        }
                    }
                    else if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }

                }
                else if ($updateMode == "inlineUpdate") {
                    // Update entity from the datagrid
                    $fieldName = $formJsonValues['fieldName'];
                    $keyFieldValue = $formJsonValues['entityKeyId'];
                    $newFieldValue = $formJsonValues['newFieldValue'];
                    $resultObject = $this->nachtraegeSkizze->updateNachtraegeSkizzeEntityField($fieldName, $keyFieldValue, $newFieldValue);
                    if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }
                    else if(is_bool($resultObject)){
                        $postbackData = Utils::formatJsonResultMessage(Common::UPDATE_INLINE_SUCCESSFUL);
                    }
                }
                return $postbackData;

            }


           /**
             * Deletes all selected entities via POST request
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteNachtraegeSkizzes($jsonData){

                // delete entity using model
                $resultObject = $this->nachtraegeSkizze->deleteSelectedNachtraegeSkizzes($jsonData);
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Deletes all entities
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteAllNachtraegeSkizzes(){

                // delete entities using corresponding model
                $resultObject = $this->nachtraegeSkizze->deleteAllNachtraegeSkizzes();
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Get dynamic page content
             * @return mixed
             */
            public function getDynamicPageContent() {

                $postbackData = "Undefined Content";
                $resultObject = null;
                switch ($this->getUserAction()) {
                    case "getAllItems":
                        $postbackData = $this->getAllNachtraegeSkizzes();
                        break;
                    case "addNewItem":
                    case "insertNewItem":
                        $jsonData = array();
                        if (isset($_POST['formValues'])) {
                            $jsonData = $_POST['formValues'][0];
                        }
                        $postbackData = $this->insertNewNachtraegeSkizze($jsonData);
                        break;
                    case "updateItem":
                        $updateMode = "allFields";
                        if (isset($_POST['updateMode'])) {
                            $updateMode = $_POST['updateMode'];
                        }
                        $skizzeId = $_POST['skizzeId'];
                        $jsonData = $_POST['formValues'][0];
                        $postbackData = $this->updateNachtraegeSkizze($skizzeId, $updateMode, $jsonData);
                        break;
                    case "deleteItem":
                        $jsonData = array();
                        if (isset($_POST['selectedIds'])) {
                            $jsonData = $_POST['selectedIds'];
                        }
                        $postbackData = $this->deleteNachtraegeSkizzes($jsonData);
                        break;
                    case "deleteAllItems":
                        $postbackData = $this->deleteAllNachtraegeSkizzes();
                        break;
                    case "editDetails":
                        $postbackData = "Undefined Content";
                        if ( isset($_POST['skizzeId']) ) {
                            $skizzeId = $_POST['skizzeId'];
                            $resultObject = $this->nachtraegeSkizze->getNachtraegeSkizzeDetails($skizzeId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                    case "viewDetails":
                    case "cancelChanges":
                        if ( isset($_POST['skizzeId']) ) {
                            $skizzeId = $_POST['skizzeId'];
                            $resultObject = $this->nachtraegeSkizze->getNachtraegeSkizzeDetails($skizzeId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                }
                return $postbackData;

            }

} 


            $userAction = null;
            if (isset($_POST) && isset($_POST['userAction'])) {
                $userAction = $_POST['userAction'];
            }
            if (!isset($userAction)) {
                echo "No action has been set";
            }
            else{
                $nachtraegeSkizzeController = new NachtraegeSkizzeController($userAction);
                $nachtraegeSkizzeController->setUserAction($userAction);
                $postbackContent = $nachtraegeSkizzeController->getDynamicPageContent();

                // send back content to client
                echo $postbackContent;
            }
            

