
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Rapport controller entity class.
 * @author
 *    Guy Bami Watcho
 */
include_once 'BaseController.php';

class RapportController extends BaseController {

    private $rapport = null;

    /**
     * Constructor of the Rapport controller 
     * @param $userAction string the user action
     * @param $userRoles array the user roles 
     */
    function __construct($userAction, $userRoles = array()) {
        parent::__construct($userAction, $userRoles);
        $this->rapport = new Rapport();
    }

    /**
     * Gets all Rapport entities
     * @return mixed object having all Rapport entities
     *    or string with the Exception details if error occured
     */
    public function getAllRapports() {

        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->rapport->selectAllRapports();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                $entitiesList .=
                        '{"rapportId":"' . $resultObject[$i]["rapportId"] . '"'
                        . ',"userId":"' . $resultObject[$i]["userId"] . '"'
                        . ',"auftragNummer":"' . $resultObject[$i]["auftragNummer"] . '"'
                        . ',"bezeichnung":"' . $resultObject[$i]["bezeichnung"] . '"'
                        . ',"datum":"' . Utils::formatShortDate($resultObject[$i]["datum"]) . '"'
                        . '}';

                if ($i != count($resultObject) - 1) {
                    $entitiesList .= $itemSperator;
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
    }

    /**
     * Inserts new Rapport entity
     * @param mixed $jsonData json object entity to insert
     * @return mixed  true if insertion was successful
     *    or string with the Exception details if error occured
     */
    public function insertNewRapport($jsonData) {

        // get json posted values from request
        $formJsonValues = $jsonData;
        $postbackData = "";
        $resultObject = null;
        // insert entity using model object
        $resultObject = $this->rapport->insertNewRapport(
                $formJsonValues['userId']
                , $formJsonValues['auftragNummer']
                , $formJsonValues['bezeichnung']
                , $formJsonValues['datum']
        );

        if (is_bool($resultObject) || is_int($resultObject)) {
            $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Updates Rapport entity via POST request
     * @param int $customerId
     * @param string $updateMode
     * @param mixed $jsonData
     * @return mixed  true if update was successful
     *    or string with the Exception details if error occured
     */
    public function updateRapport($rapportId, $updateMode, $jsonData) {

        // get json posted values from request
        //$formJsonValues = json_decode($jsonData, true);
        $formJsonValues = $jsonData;
        $postbackData = "";
        $resultObject = null;
        if ($updateMode == "allFields") {
            // update all entity fields
            $resultObject = $this->rapport->updateRapportDetails(
                    $rapportId
                    , $formJsonValues['userId']
                    , $formJsonValues['auftragNummer']
                    , $formJsonValues['bezeichnung']
                    , $formJsonValues['datum']
            );
            if (is_bool($resultObject)) {
                if ($resultObject == true) {
                    $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_SUCCESSFUL);
                } else {
                    $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_FAILED);
                }
            } else if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            }
        } else if ($updateMode == "inlineUpdate") {
            // Update entity from the datagrid
            $fieldName = $formJsonValues['fieldName'];
            $keyFieldValue = $formJsonValues['entityKeyId'];
            $newFieldValue = $formJsonValues['newFieldValue'];
            $resultObject = $this->rapport->updateRapportEntityField($fieldName, $keyFieldValue, $newFieldValue);
            if (is_string($resultObject)) {
                //error occured
                $postbackData = Utils::formatJsonErrorMessage($resultObject);
            } else if (is_bool($resultObject)) {
                $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_INLINE_SUCCESSFUL);
            }
        }
        return $postbackData;
    }

    /**
     * Deletes all selected entities via POST request
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteRapports($jsonData) {

        // delete entity using model
        $resultObject = $this->rapport->deleteSelectedRapports($jsonData);
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }

    /**
     * Deletes all entities
     * @param mixed $jsonData all entities Id to delete
     * @return mixed
     */
    public function deleteAllRapports() {

        // delete entities using corresponding model
        $resultObject = $this->rapport->deleteAllRapports();
        if (is_bool($resultObject)) {
            if ($resultObject == true) {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
            } else {
                $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
            }
        } else if (is_string($resultObject)) {
            //error occured
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        } else {
            $postbackData = Utils::formatJsonErrorMessage($resultObject);
        }
        return $postbackData;
    }
    
    public function getAllRapportsByUser($jsonData) {
         
        $formJsonValues = $jsonData;
        $itemSperator = ",";
        $entitiesList = "";
        $resultObject = $this->rapport->selectAllRapports();
        if (is_string($resultObject)) {
            return Utils::formatJsonErrorMessage($resultObject);
        } else if (is_array($resultObject)) {
            for ($i = 0; $i < count($resultObject); $i++) {
                if($resultObject[$i]["userId"] == $formJsonValues['userId']){
                    
                    $entitiesList .=
                            '{"rapportId":"' . $resultObject[$i]["rapportId"] . '"'
                            . ',"userId":"' . $resultObject[$i]["userId"] . '"'
                            . ',"auftragNummer":"' . $resultObject[$i]["auftragNummer"] . '"'
                            . ',"bezeichnung":"' . $resultObject[$i]["bezeichnung"] . '"'
                            . ',"datum":"' . Utils::formatShortDate($resultObject[$i]["datum"]) . '"'
                            . '}';
    
                    if ($i != count($resultObject) - 1) {
                        $entitiesList .= $itemSperator;
                    }
                }
            }
            // close json list
            $entitiesList = "[" . $entitiesList . "]";
        }
        return $entitiesList;
        
	 
    }


    /**
     * Get dynamic page content
     * @return mixed
     */
    public function getDynamicPageContent() {

        $postbackData = "Undefined Content";
        $resultObject = null;
        switch ($this->getUserAction()) {
            case "getAllItems":
                $postbackData = $this->getAllRapports();
                break;
            case "addNewItem":
            case "insertNewItem":
                $jsonData = array();
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->insertNewRapport($jsonData);
                break;
            case "updateItem":
                $updateMode = "allFields";
                if (isset($_POST['updateMode'])) {
                    $updateMode = $_POST['updateMode'];
                }
                $rapportId = $_POST['rapportId'];
                $jsonData = $_POST['formValues'][0];
                $postbackData = $this->updateRapport($rapportId, $updateMode, $jsonData);
                break;
            case "deleteItem":
            case "deleteItems":
                $jsonData = array();
                if (isset($_POST['selectedIds'])) {
                    $jsonData = $_POST['selectedIds'];
                }
                $postbackData = $this->deleteRapports($jsonData[0]);
                break;
            case "deleteAllItems":
                $postbackData = $this->deleteAllRapports();
                break;
            case "editDetails":
                $postbackData = "Undefined Content";
                if (isset($_POST['rapportId'])) {
                    $rapportId = $_POST['rapportId'];
                    $resultObject = $this->rapport->getRapportDetails($rapportId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "viewDetails":
            case "cancelChanges":
                if (isset($_POST['rapportId'])) {
                    $rapportId = $_POST['rapportId'];
                    $resultObject = $this->rapport->getRapportDetails($rapportId);
                }
                if (is_string($resultObject)) {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                } else if (is_array($resultObject)) {
                    $postbackData = Utils::convertArrayToJson($resultObject[0]);
                }
                break;
            case "getAllRapportsByUser":
                if (isset($_POST['formValues'])) {
                    $jsonData = $_POST['formValues'][0];
                }
                $postbackData = $this->getAllRapportsByUser($jsonData);
                break;
        }
        return $postbackData;
    }

}


function testAddNewItem() {
    $t = Utils::generateItemRefenceNumber(5);
    $jsonRaw = '{"userAction":"addNewItem", "formValues":'
            . '[{"userId":"1"'
            . ',"auftragNummer":"auftragNummer-1323"'
            . ',"bezeichnung":"bezeichnung-1323"'
            . ',"datum":"2020-03-12 14:33:11"'
            . ' }]
              }';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testGetAllItems() {

    $jsonRaw = '{"userAction":"getAllItems"}';

    if (is_string($jsonRaw)) {
        $_POST = json_decode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testUpdateItem() {

    $jsonRaw = '{"userAction":"updateItem", "rapportId":"1", "formValues":'
            . '[{"userId":"1"'
            . ',"auftragNummer":"new-auftragNummer-1323"'
            . ',"bezeichnung":"new-bezeichnung-1323"'
            . ',"datum":"2020-03-11 16:33:11"'
            . ' }]
              }';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testDeleteItem() {

    $jsonRaw = '{"selectedIds":[{"rapportId":"3"}], "userAction":"deleteItems"}';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

function testGetAllRapportsByUser() {

    $jsonRaw = '{"userAction":"getAllRapportsByUser", "formValues":'
            . '[{"userId":"1"'
            
            . ' }]
              }';

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}

//testAddNewItem();
//testUpdateItem();
//testGetAllItems();
//estDeleteItem();
//testGetAllRapportsByUser();




if ($_SERVER['CONTENT_TYPE'] === "application/json; charset=UTF-8" || $_SERVER['CONTENT_TYPE'] === "application/json") {
    $jsonRaw = file_get_contents('php://input');

    if (is_string($jsonRaw)) {
        $_POST = Utils::jsonDecode($jsonRaw, true);
    } else {
        $_POST = $jsonRaw;
    }
}


$userAction = null;
if (isset($_POST) && isset($_POST['userAction'])) {
    $userAction = $_POST['userAction'];
}
else if (isset($_GET) && isset($_GET['userAction'])) {
    $userAction = $_GET['userAction'];
}
if (!isset($userAction)) {
    echo "No action has been set";
} 
else {
    Utils::logRequestToFile($userAction);
    $rapportController = new RapportController($userAction);
    $rapportController->setUserAction($userAction);
    $postbackContent = $rapportController->getDynamicPageContent();

    // send back content to client
    echo $postbackContent;
}
            

