
<?php

/**
 * This module was auto generated by GWatcho-Code generator
 * The Project controller entity class.
 * @author
 *    Guy Bami Watcho
 */
 
 include_once dirname(__DIR__) . DIRECTORY_SEPARATOR .  join(DIRECTORY_SEPARATOR, array('Includes', 'Utils.php'));

   
//echo "Common::$UPDATE_SUCCESSFUL" . Common::$UPDATE_SUCCESSFUL;

            
//testAddNewItem();
//testGetAllItems();           

//testDeleteItem();
Utils::logRequestToFile("Uploading file....");

$file_path = "../UploadedFiles/TaskReports/";

if(isset($_POST['destinationDir'])){
    $file_path = "../UploadedFiles/" . $_POST['destinationDir'] . "/";
}

$file_path = $file_path . basename($_FILES['uploaded_file']['name']);
Utils::logRequestToFile("File sent: " . $file_path);

if(move_uploaded_file($_FILES['uploaded_file']['tmp_name'], $file_path)){
    Utils::logRequestToFile("Uploading SUCCESS....");
    //echo "Sucess";
    echo '{"uploadResult":"success_ok"}';
    
}
else{
    Utils::logRequestToFile("Uploading FAILED....");
    echo "Error occured in upload...";
}
            
