
            <?php 


               /**
                * This module was auto generated by GWatcho-Code generator
                * The TaskLogTime controller entity class.
                * @author
                *    Guy Bami Watcho
                */

  
include_once 'BaseController.php';


 class TaskLogTimeController extends BaseController { 
private $taskLogTime = null; 


                 /**
                  *Constructor of the TaskLogTime controller 

                   * @param $userAction string the user action
* @param $userRoles array the user roles 
                  */
                
function __construct($userAction, $userRoles = array()){ 
     parent::__construct($userAction, $userRoles);
                        $this->taskLogTime = new TaskLogTime(); }


           /**
            * Gets all TaskLogTime entities
            * @return mixed object having all TaskLogTime entities
            *    or string with the Exception details if error occured
            */
            public function getAllTaskLogTimes(){

                $itemSperator = ",";
                $entitiesList = "";
                $resultObject = $this->taskLogTime->selectAllTaskLogTimes();
                if(is_string($resultObject)){
                    return Utils::formatJsonErrorMessage($resultObject);
                }
                else if(is_array($resultObject)){
                    for ($i = 0; $i < count($resultObject); $i++)
                    {
                        $entitiesList .= 
'{"taskLogTimeId":"'.$resultObject[$i]["taskLogTimeId"].'"'
.',"userId":"'.$resultObject[$i]["userId"].'"'
.',"taskId":"'.$resultObject[$i]["taskId"].'"'
.',"title":"'.$resultObject[$i]["title"].'"'
.',"startTime":"'.$resultObject[$i]["startTime"].'"'
.',"endTime":"'.$resultObject[$i]["endTime"].'"'
.',"summary":"'.$resultObject[$i]["summary"].'"'
.',"date":"'.$resultObject[$i]["date"].'"'
.'}';

                        if ($i != count($resultObject) - 1) {
                            $entitiesList .= $itemSperator;
                        }
                    }
                    // close json list
                    $entitiesList = "[" . $entitiesList . "]";

                }
                return $entitiesList;

            }


           /**
             * Inserts new TaskLogTime entity
             * @param mixed $jsonData json object entity to insert
             * @return mixed  true if insertion was successful
             *    or string with the Exception details if error occured
             */
            public function insertNewTaskLogTime($jsonData){

                // get json posted values from request
                //$formJsonValues = json_decode($jsonData, true);
                $formJsonValues = $jsonData;
                $postbackData = "";
                $resultObject = null;
                // insert entity using model object
                $resultObject = $this->taskLogTime->insertNewTaskLogTime(
                                $formJsonValues['userId']
,$formJsonValues['taskId']
,$formJsonValues['title']
,$formJsonValues['startTime']
,$formJsonValues['endTime']
,$formJsonValues['summary']
,$formJsonValues['date']


                );

                if(is_bool($resultObject) || is_int($resultObject)){
                    $postbackData = Utils::formatJsonMessage("insertedItemKey", $resultObject);
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Updates TaskLogTime entity via POST request
             * @param int $customerId
             * @param string $updateMode
             * @param mixed $jsonData
             * @return mixed  true if update was successful
             *    or string with the Exception details if error occured
             */
            public function updateTaskLogTime($taskLogTimeId, $updateMode, $jsonData){

                // get json posted values from request
                //$formJsonValues = json_decode($jsonData, true);
                $formJsonValues = $jsonData;
                $postbackData = "";
                $resultObject = null;
                if ($updateMode == "allFields") {
                    // update all entity fields
                    $resultObject = $this->taskLogTime->updateTaskLogTimeDetails(
                                  $taskLogTimeId
,$formJsonValues['userId']
,$formJsonValues['taskId']
,$formJsonValues['title']
,$formJsonValues['startTime']
,$formJsonValues['endTime']
,$formJsonValues['summary']
,$formJsonValues['date']


                    );
                    if(is_bool($resultObject)){
                        if($resultObject == true){
                            $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_SUCCESSFUL);
                        }
                        else{
                            $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_FAILED);
                        }
                    }
                    else if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }

                }
                else if ($updateMode == "inlineUpdate") {
                    // Update entity from the datagrid
                    $fieldName = $formJsonValues['fieldName'];
                    $keyFieldValue = $formJsonValues['entityKeyId'];
                    $newFieldValue = $formJsonValues['newFieldValue'];
                    $resultObject = $this->taskLogTime->updateTaskLogTimeEntityField($fieldName, $keyFieldValue, $newFieldValue);
                    if(is_string($resultObject)){
                        //error occured
                        $postbackData = Utils::formatJsonErrorMessage($resultObject);
                    }
                    else if(is_bool($resultObject)){
                        $postbackData = Utils::formatJsonResultMessage(Common::$UPDATE_INLINE_SUCCESSFUL);
                    }
                }
                return $postbackData;

            }


           /**
             * Deletes all selected entities via POST request
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteTaskLogTimes($jsonData){

                // delete entity using model
                $resultObject = $this->taskLogTime->deleteSelectedTaskLogTimes($jsonData);
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Deletes all entities
             * @param mixed $jsonData all entities Id to delete
             * @return mixed
             */
            public function deleteAllTaskLogTimes(){

                // delete entities using corresponding model
                $resultObject = $this->taskLogTime->deleteAllTaskLogTimes();
                if(is_bool($resultObject)){
                    if($resultObject == true){
                        $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_SUCCESSFUL);
                    }
                    else{
                        $postbackData = Utils::formatJsonResultMessage(Common::$DELETE_FAILED);
                    }
                }
                else if(is_string($resultObject)){
                    //error occured
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                else {
                    $postbackData = Utils::formatJsonErrorMessage($resultObject);
                }
                return $postbackData;

            }


           /**
             * Get dynamic page content
             * @return mixed
             */
            public function getDynamicPageContent() {

                $postbackData = "Undefined Content";
                $resultObject = null;
                switch ($this->getUserAction()) {
                    case "getAllItems":
                        $postbackData = $this->getAllTaskLogTimes();
                        break;
                    case "addNewItem":
                    case "insertNewItem":
                        $jsonData = array();
                        if (isset($_POST['formValues'])) {
                            $jsonData = $_POST['formValues'][0];
                        }
                        $postbackData = $this->insertNewTaskLogTime($jsonData);
                        break;
                    case "updateItem":
                        $updateMode = "allFields";
                        if (isset($_POST['updateMode'])) {
                            $updateMode = $_POST['updateMode'];
                        }
                        $taskLogTimeId = $_POST['taskLogTimeId'];
                        $jsonData = $_POST['formValues'][0];
                        $postbackData = $this->updateTaskLogTime($taskLogTimeId, $updateMode, $jsonData);
                        break;
                    case "deleteItem":
                        $jsonData = array();
                        if (isset($_POST['selectedIds'])) {
                            $jsonData = $_POST['selectedIds'];
                        }
                        $postbackData = $this->deleteTaskLogTimes($jsonData);
                        break;
                    case "deleteAllItems":
                        $postbackData = $this->deleteAllTaskLogTimes();
                        break;
                    case "editDetails":
                        $postbackData = "Undefined Content";
                        if ( isset($_POST['taskLogTimeId']) ) {
                            $taskLogTimeId = $_POST['taskLogTimeId'];
                            $resultObject = $this->taskLogTime->getTaskLogTimeDetails($taskLogTimeId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                    case "viewDetails":
                    case "cancelChanges":
                        if ( isset($_POST['taskLogTimeId']) ) {
                            $taskLogTimeId = $_POST['taskLogTimeId'];
                            $resultObject = $this->taskLogTime->getTaskLogTimeDetails($taskLogTimeId);
                        }
                        if(is_string($resultObject)){
                            $postbackData = Utils::formatJsonErrorMessage($resultObject);
                        }
                        else if(is_array($resultObject)){
                            $postbackData = Utils::convertArrayToJson($resultObject[0]);
                        }
                        break;
                }
                return $postbackData;

            }

} 



            if ($_SERVER['CONTENT_TYPE'] === "application/json; charset=UTF-8" || $_SERVER['CONTENT_TYPE'] === "application/json") {
                $jsonRaw = file_get_contents("php://input");

                if (is_string($jsonRaw)) {
                    $_POST = Utils::jsonDecode($jsonRaw, true);
                } else {
                    $_POST = $jsonRaw;
                }
            }

            $userAction = null;
            if (isset($_POST) && isset($_POST['userAction'])) {
                $userAction = $_POST['userAction'];
            }
            else if (isset($_GET) && isset($_GET['userAction'])) {
                $userAction = $_GET['userAction'];
            }
            if (!isset($userAction)) {
                echo "No action has been set";
            }
            else{
                Utils::logRequestToFile($userAction);
                $taskLogTimeController = new TaskLogTimeController($userAction);
                $taskLogTimeController->setUserAction($userAction);
                $postbackContent = $taskLogTimeController->getDynamicPageContent();

                // send back content to client
                echo $postbackContent;
            }
            

