
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The AufMasseSkizze model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class AufMasseSkizze {

    private $skizzeId;
    private $aufmasseId;
    private $dateiName;

    /** Constructor of an AufMasseSkizze object
     *  @param $skizzeId int The entity  primary key field 
     * @param  $aufmasseId int The entity  aufmasseId field 
     * @param  $dateiName string The entity  dateiName field 
     */
    function __construct($skizzeId = "", $aufmasseId = "", $dateiName = "") {
        $this->skizzeId = $skizzeId;
        $this->aufmasseId = $aufmasseId;
        $this->dateiName = $dateiName;
    }

    /**
     * Gets  $aufmasseId value
     * @param $aufmasseId
     * @return mixed
     */
    public function getAufmasseId() {
        return $this->aufmasseId;
    }

    /**
     * Gets  $dateiName value
     * @param $dateiName
     * @return mixed
     */
    public function getDateiName() {
        return $this->dateiName;
    }

    /**
     * Sets  $aufmasseId value
     * @param $aufmasseId
     * @return void
     */
    public function setAufmasseId($aufmasseId) {
        $this->aufmasseId = $aufmasseId;
    }

    /**
     * Sets  $dateiName value
     * @param $dateiName
     * @return void
     */
    public function setDateiName($dateiName) {
        $this->dateiName = $dateiName;
    }

    /**
     * Selects all AufMasseSkizze items
     * @return
     *   array The object having all AufMasseSkizze items
     *    or string with the Exception details if error occured
     */
    public function selectAllAufMasseSkizzes() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllAufMasseSkizzes();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets AufMasseSkizze item
     * @param $skizzeId int  The table primary key
     * @return
     *   array The object with the given $skizzeId value
     */
    public function getAufMasseSkizzeDetails($skizzeId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAufMasseSkizzeDetails($skizzeId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new AufMasseSkizze entity
     * @param  $aufmasseId int The entity  aufmasseId field 
     * @param   $dateiName string The entity  dateiName field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewAufMasseSkizze($aufmasseId, $dateiName) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewAufMasseSkizze($aufmasseId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates AufMasseSkizze item
     * @param  $skizzeId int The entity  skizzeId field 
     * @param  $aufmasseId int The entity  aufmasseId field 
     * @param  $dateiName string The entity  dateiName field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateAufMasseSkizze($skizzeId, $aufmasseId, $dateiName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateAufMasseSkizze($skizzeId, $aufmasseId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates AufMasseSkizze item  details

     * @param  $skizzeId int The entity  skizzeId field 
     * @param  $aufmasseId int The entity  aufmasseId field 
     * @param  $dateiName string The entity  dateiName field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateAufMasseSkizzeDetails($skizzeId, $aufmasseId, $dateiName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateAufMasseSkizzeDetails($skizzeId, $aufmasseId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates aufmasseId of the AufMasseSkizze entity
     * @param   $skizzeId int The entity  skizzeId field 
     * @param   $aufmasseId int The entity  aufmasseId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateAufMasseSkizzeAufmasseId($skizzeId, $aufmasseId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateAufMasseSkizzeAufmasseId($skizzeId, $aufmasseId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates dateiName of the AufMasseSkizze entity
     * @param   $skizzeId int The entity  skizzeId field 
     * @param   $dateiName string The entity  dateiName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateAufMasseSkizzeDateiName($skizzeId, $dateiName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateAufMasseSkizzeDateiName($skizzeId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the AufMasseSkizze item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateAufMasseSkizzeEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "aufmasseId":
                    return $this->updateAufMasseSkizzeAufmasseId($keyFieldValue, $newFieldValue);

                case "dateiName":
                    return $this->updateAufMasseSkizzeDateiName($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes AufMasseSkizze item
     * @param  $skizzeId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAufMasseSkizze($skizzeId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAufMasseSkizze($skizzeId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected AufMasseSkizze items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedAufMasseSkizzes($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteAufMasseSkizze($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete AufMasseSkizze !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all AufMasseSkizze items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllAufMasseSkizzes() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllAufMasseSkizzes();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
