
<?php

/**
 * This module was auto generated by the G-Watcho module generator
 * The NachtragBild model entity class.
 * @author
 *    Guy Bami
 */
include_once '../Utils/ExceptionLogger.php';

class NachtragBild {

    private $bildId;
    private $nachtragId;
    private $dateiName;

    /** Constructor of an NachtragBild object
     *  @param $bildId int The entity  primary key field 
     * @param  $nachtragId int The entity  nachtragId field 
     * @param  $dateiName string The entity  dateiName field 
     */
    function __construct($bildId = "", $nachtragId = "", $dateiName = "") {
        $this->bildId = $bildId;
        $this->nachtragId = $nachtragId;
        $this->dateiName = $dateiName;
    }

    /**
     * Gets  $nachtragId value
     * @param $nachtragId
     * @return mixed
     */
    public function getNachtragId() {
        return $this->nachtragId;
    }

    /**
     * Gets  $dateiName value
     * @param $dateiName
     * @return mixed
     */
    public function getDateiName() {
        return $this->dateiName;
    }

    /**
     * Sets  $nachtragId value
     * @param $nachtragId
     * @return void
     */
    public function setNachtragId($nachtragId) {
        $this->nachtragId = $nachtragId;
    }

    /**
     * Sets  $dateiName value
     * @param $dateiName
     * @return void
     */
    public function setDateiName($dateiName) {
        $this->dateiName = $dateiName;
    }

    /**
     * Selects all NachtragBild items
     * @return
     *   array The object having all NachtragBild items
     *    or string with the Exception details if error occured
     */
    public function selectAllNachtragBilds() {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectAllNachtragBilds();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Gets NachtragBild item
     * @param $bildId int  The table primary key
     * @return
     *   array The object with the given $bildId value
     */
    public function getNachtragBildDetails($bildId) {
        try {
            $daoSelect = new DaoSelect();
            return $daoSelect->selectNachtragBildDetails($bildId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Inserts new NachtragBild entity
     * @param  $nachtragId int The entity  nachtragId field 
     * @param   $dateiName string The entity  dateiName field
     * @return
     *   boolean TRUE if insert successful, otherwise FALSE
     */
    public function insertNewNachtragBild($nachtragId, $dateiName) {
        try {
            $daoInsert = new DaoInsert();
            return $daoInsert->insertNewNachtragBild($nachtragId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates NachtragBild item
     * @param  $bildId int The entity  bildId field 
     * @param  $nachtragId int The entity  nachtragId field 
     * @param  $dateiName string The entity  dateiName field 
     * @return
     *   boolean  TRUE if update successful, otherwise FALSE
     */
    public function updateNachtragBild($bildId, $nachtragId, $dateiName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateNachtragBild($bildId, $nachtragId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates NachtragBild item  details

     * @param  $bildId int The entity  bildId field 
     * @param  $nachtragId int The entity  nachtragId field 
     * @param  $dateiName string The entity  dateiName field 
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateNachtragBildDetails($bildId, $nachtragId, $dateiName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateNachtragBildDetails($bildId, $nachtragId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates nachtragId of the NachtragBild entity
     * @param   $bildId int The entity  bildId field 
     * @param   $nachtragId int The entity  nachtragId field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateNachtragBildNachtragId($bildId, $nachtragId) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateNachtragBildNachtragId($bildId, $nachtragId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates dateiName of the NachtragBild entity
     * @param   $bildId int The entity  bildId field 
     * @param   $dateiName string The entity  dateiName field
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateNachtragBildDateiName($bildId, $dateiName) {
        try {
            $daoUpdate = new DaoUpdate();
            return $daoUpdate->updateNachtragBildDateiName($bildId, $dateiName);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Updates specific field of the NachtragBild item
     * @param    $fieldName string The field name
     * @param    $keyFieldValue int The primary key field value
     * @param    $newFieldValue string The new field value
     * @return
     *   boolean TRUE if update successful, otherwise FALSE
     */
    public function updateNachtragBildEntityField($fieldName, $keyFieldValue, $newFieldValue) {
        try {
            switch ($fieldName) {

                case "nachtragId":
                    return $this->updateNachtragBildNachtragId($keyFieldValue, $newFieldValue);

                case "dateiName":
                    return $this->updateNachtragBildDateiName($keyFieldValue, $newFieldValue);
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes NachtragBild item
     * @param  $bildId int  The table primary key
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteNachtragBild($bildId) {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteNachtragBild($bildId);
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

    /**
     * Deletes selected NachtragBild items
     * @param  $selectedItemsId array The List of primary keys item to be deleted
     * @return boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteSelectedNachtragBilds($selectedItemsId) {

        try {
            $daoDelete = new DaoDelete();
            if (!isset($selectedItemsId) || !is_array($selectedItemsId)) {
                return "Error: Invalid Parameters type for this method.";
            }
            foreach (array_values($selectedItemsId) as $itemId) {
                if ($daoDelete->deleteNachtragBild($itemId)) {
                    continue;
                } else {
                    return "error: Can not delete NachtragBild !";
                }
            }
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
        return true;
    }

    /**
     * Deletes all NachtragBild items
     * @return    boolean|mixed TRUE if delete successful, otherwise string with error message
     */
    public function deleteAllNachtragBilds() {
        try {
            $daoDelete = new DaoDelete();
            return $daoDelete->deleteAllNachtragBilds();
        } catch (ExceptionLogger $e) {
            return $e->getErrorMessage();
        }
    }

}
